//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingCorp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Book_id { get; set; }
        public string Book_name { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> RegistrationTime { get; set; }
        public string Category { get; set; }
        public string Book_description { get; set; }
    }
}
